import { TRPCReactProvider } from '@/client/providers/trpc-react-provider';
import '@/styles/main.scss';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Url shortener',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className}`}>
				<TRPCReactProvider cookies={cookies().toString()}>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
