import ReduxProvider from '@/client/providers/redux-provider';
import { TRPCReactProvider } from '@/client/providers/trpc-react-provider';
import '@/styles/main.scss';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { type ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Url shortener',
	description: 'Generated by create-t3-app',
};

export default function RootLayout({
	children,
}: {
	children: ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className}`}>
				<TRPCReactProvider cookies={cookies().toString()}>
					<ReduxProvider>{children}</ReduxProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
